# Generated by Django 4.2.18 on 2025-03-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chembook', '0016_remove_stage_next_stage_remove_stage_pathway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_stages', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('main_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chembook.substance')),
            ],
            options={
                'permissions': [('add_pathway', 'Може додавати шляхи синтезу'), ('add_stage', 'Може додавати стадії синтезу')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.PositiveIntegerField(default=0)),
                ('next_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='chemhub.stage')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='chemhub.pathway')),
                ('prev_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='chemhub.stage')),
                ('reaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_in_stages', to='chembook.reaction')),
            ],
            options={
                'ordering': ['pathway', 'order_number'],
            },
        ),
        migrations.AddField(
            model_name='pathway',
            name='synthesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='chemhub.synthesis'),
        ),
    ]
