# Generated by Django 4.2.19 on 2025-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
