# Generated by Django 4.2.19 on 2025-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0002_reaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='substance',
            name='smiles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
