# Generated by Django 4.2.19 on 2025-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0003_substance_image_substance_smiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='substances',
            field=models.ManyToManyField(blank=True, to='chembook.substance'),
        ),
    ]
