# Generated by Django 4.2.18 on 2025-03-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0004_alter_reaction_substances'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'default_permissions': ('add', 'delete', 'change', 'view'), 'permissions': []},
        ),
    ]
