# Generated by Django 4.2.18 on 2025-03-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0007_batch_substance_molecular_mass_alter_reaction_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_permissions': ('add', 'delete', 'change', 'view'), 'permissions': []},
        ),
    ]
