# Generated by Django 4.2.18 on 2025-03-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0008_alter_batch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'default_permissions': ('add', 'delete', 'change', 'view'), 'permissions': [('add_batch', 'Може створювати бетчі для цієї реакції')]},
        ),
    ]
