# Generated by Django 4.2.18 on 2025-03-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0009_alter_reaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producing_reactions', to='chembook.substance'),
        ),
    ]
