# Generated by Django 4.2.18 on 2025-03-13 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chembook', '0010_reaction_main_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'default_permissions': ('delete', 'change', 'view'), 'permissions': [('add_batch', 'Може створювати бетчі для цієї реакції')]},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_stages', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheses', to=settings.AUTH_USER_MODEL)),
                ('main_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producing_syntheses', to='chembook.substance')),
            ],
            options={
                'permissions': [('add_reaction', 'Може створювати реакції в цьому синтезі'), ('add_pathway', 'Може додавати шляхи синтезу'), ('add_stage', 'Може додавати стадії синтезу')],
                'default_permissions': ('delete', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('next_reaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions_used_to_obtain', to='chembook.reaction')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='chembook.pathway')),
                ('previous_reaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='chembook.reaction')),
                ('reaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_in_stages', to='chembook.reaction')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='synthesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='chembook.synthesis'),
        ),
    ]
