# Generated by Django 4.2.18 on 2025-03-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0011_pathway_alter_reaction_options_alter_reaction_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['pathway', 'order_number']},
        ),
        migrations.AlterModelOptions(
            name='synthesis',
            options={'default_permissions': ('delete', 'change', 'view'), 'permissions': [('add_pathway', 'Може додавати шляхи синтезу'), ('add_stage', 'Може додавати стадії синтезу')]},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='next_reaction',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='number',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='previous_reaction',
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='chembook.stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='prev_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='chembook.stage'),
        ),
    ]
