# Generated by Django 4.2.18 on 2025-03-17 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chembook', '0012_alter_stage_options_alter_synthesis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_permissions': ('delete', 'change', 'view')},
        ),
        migrations.AlterModelOptions(
            name='synthesis',
            options={'permissions': [('add_pathway', 'Може додавати шляхи синтезу'), ('add_stage', 'Може додавати стадії синтезу')]},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='is_probe',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='substances',
        ),
        migrations.AddField(
            model_name='batch',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chembook.substance'),
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_substances',
            field=models.ManyToManyField(blank=True, related_name='reaction_usages', to='chembook.substance'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chembook.substance'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chembook.substance'),
        ),
    ]
