# Generated by Django 4.2.18 on 2025-03-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0013_alter_batch_options_alter_synthesis_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction_substances',
            new_name='substances',
        ),
    ]
