# Generated by Django 4.2.18 on 2025-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0014_rename_reaction_substances_reaction_substances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synthesis',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
