# Generated by Django 4.2.18 on 2025-03-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembook', '0015_alter_batch_description_alter_batch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='pathway',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='prev_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='synthesis',
            name='author',
        ),
        migrations.RemoveField(
            model_name='synthesis',
            name='main_product',
        ),
        migrations.DeleteModel(
            name='Pathway',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Synthesis',
        ),
    ]
