# Generated by Django 4.2.18 on 2025-04-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0002_standarduser_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='manager',
        ),
    ]
